# Generated by Django 5.2.8 on 2025-11-14 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DailyNutrition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("total_calories", models.PositiveIntegerField(default=0)),
                (
                    "total_protein",
                    models.DecimalField(decimal_places=1, default=0, max_digits=6),
                ),
                (
                    "total_carbs",
                    models.DecimalField(decimal_places=1, default=0, max_digits=6),
                ),
                (
                    "total_fats",
                    models.DecimalField(decimal_places=1, default=0, max_digits=6),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Meal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("BREAKFAST", "Breakfast"),
                            ("LUNCH", "Lunch"),
                            ("DINNER", "Dinner"),
                            ("SNACK", "Snack"),
                        ],
                        max_length=10,
                    ),
                ),
                ("calories", models.PositiveIntegerField()),
                (
                    "protein",
                    models.DecimalField(decimal_places=1, default=0, max_digits=5),
                ),
                (
                    "carbs",
                    models.DecimalField(decimal_places=1, default=0, max_digits=5),
                ),
                (
                    "fats",
                    models.DecimalField(decimal_places=1, default=0, max_digits=5),
                ),
                ("date", models.DateField()),
                ("consumed_at", models.TimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-date", "meal_type"],
            },
        ),
    ]
